import { createRoot } from "react-dom/client";
import { AppShell } from "@/components/app-shell";
import { TrainerForm } from "@/components/users/trainer-form";
import { RecordReviewTable } from "@/components/review/record-review-table";
import { ConnectionControls } from "@/components/review/connection-controls";
import { MappingWorkspace } from "@/components/review/mapping-workspace";
import type { MappingResult } from "@/features/mapping/types";
import "@/app/globals.css";
import "@/components/dashboard/dashboard.css";
import "@/components/review/admin.css";
window.fetch = async () => new Response(JSON.stringify({ result: {} }), { status: 200 });
const connection = { id: "fictional-sheet", display_name: "샘플 트레이너 A 운영 시트", is_active: false, trainer_id: "fictional-trainer", trainer_assignment_mode: "direct" as const };
const trainers = [{ id: "fictional-trainer", display_name: "샘플 트레이너 A", email: "coach-a@example.com", is_active: true, claimed: true }, { id: "fictional-invite", display_name: "샘플 트레이너 B", email: "coach-b@example.com", is_active: false, claimed: false }];
const input = { organizationId:"fictional-org", sourceConnectionId:connection.id, sourceTabId:"fictional-tab", tabTitle:"회원 관리 원본", domain:"member" as const, rows:[["회원명","연락처","잔여횟수"],["샘플 회원","1234","미확인"]] };
const mappingResult: MappingResult = { domain:"member",headerRowIndex:0,confidence:.8,unmappedHeaders:["잔여횟수"],missingRequiredFields:[],mappingFingerprint:"fixture",fields:["name","phone_last4",null].map((field,index) => ({ columnIndex:index,sourceHeader:input.rows[0][index],normalizedHeader:input.rows[0][index],sampleValues:[input.rows[1][index]],field,proposedField:field ?? "remaining_sessions",confidence:field ? 1 : .3,margin:1,match:"exact",reason:field ? "accepted" : "type-conflict",profile:{ kind:"freeText",nonEmptyCount:1,confidence:1,ratios:{date:0,integer:0,money:0,percentage:0,status:0,identifier:0,freeText:1} } })) };
const users = location.search.includes("users");
createRoot(document.getElementById("root")!).render(<AppShell role="admin" displayName="샘플 관리자" title={users ? "사용자 관리" : "데이터 점검"}><div className="admin-stack"><p className="sample-banner">로컬 QA 전용 · 모든 데이터는 가상 예시입니다. 실제 변경은 전송하지 않습니다.</p>{users ? <TrainerForm trainers={trainers} connections={[connection]} /> : <><RecordReviewTable records={[{ id:"fictional-record", name:"샘플 회원", domain:"member", tab_title:"회원 관리 원본", record_status:"review_required", phone_last4:"1234", remaining_sessions:null, issues:[{ field:"remaining_sessions", code:"invalid_number", message:"invalid_number" }], source_fields:[{ sourceHeader:"잔여횟수", field:"remaining_sessions" }] }]} members={[{ id:"fictional-keep",name:"샘플 유지 회원",external_member_id:"M001",source_record_key:"fixture-key" }]} /><MappingWorkspace tabs={[{ id:input.sourceTabId, source_connection_id:connection.id,title:input.tabTitle,domain:"member",mappingResult }]} /><section className="admin-section"><h2>원본 이력</h2><ConnectionControls connection={connection} /></section></>}</div></AppShell>);
